import { useEffect, useState } from 'react'
import type { AuthUser } from '../auth/store'
import { PageIntro } from '../components/ui'
import { apiUrl } from '../config'

export function AdminUsersPage({ token, setToast }: { token: string | null; setToast: (value: string) => void }) {
  const [users, setUsers] = useState<AuthUser[]>([]); const [query, setQuery] = useState(''); const [role, setRole] = useState(''); const [status, setStatus] = useState(''); const [selected, setSelected] = useState<AuthUser | null>(null); const [audit, setAudit] = useState<{ action: string; createdAt: string }[]>([])
  const headers: Record<string, string> = token ? { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' } : {}
  const load = async () => { if (!token) return; const p = new URLSearchParams(); if (query) p.set('q', query); if (role) p.set('role', role); if (status) p.set('status', status); const res = await fetch(apiUrl(`/api/admin/users?${p}`), { headers }); const body = await res.json(); if (!res.ok || !body.ok) return setToast(body.error ?? 'Could not load users.'); setUsers(body.users) }
  useEffect(() => { void load() }, [token, query, role, status])
  const access = async (user: AuthUser, data: Record<string, string>) => { if (!window.confirm(`Apply this change to ${user.name}?`)) return; const res = await fetch(apiUrl(`/api/admin/users/${user.id}/access`), { method: 'PATCH', headers, body: JSON.stringify(data) }); const body = await res.json(); if (!res.ok || !body.ok) return setToast(body.error ?? 'Could not update the account.'); setToast('Account updated.'); void load() }
  const inspect = async (user: AuthUser) => { setSelected(user); const res = await fetch(apiUrl(`/api/admin/users/${user.id}/audit`), { headers }); const body = await res.json(); setAudit(body.history ?? []) }
  const resend = async (user: AuthUser) => { const res = await fetch(apiUrl(`/api/admin/users/${user.id}/resend-verification`), { method: 'POST', headers }); const body = await res.json(); setToast(body.ok ? 'Verification code reissued.' : body.error) }
  return <PageIntro eyebrow="LIBRARY ADMINISTRATION" title="Users & permissions" copy="Search accounts, change access, and review account activity.">
    <section className="admin-resource-card"><div className="admin-filters"><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search name, email, or ID" /><select value={role} onChange={e => setRole(e.target.value)}><option value="">All roles</option><option value="student">Student</option><option value="lecturer">Lecturer</option><option value="administrator">Administrator</option></select><select value={status} onChange={e => setStatus(e.target.value)}><option value="">All statuses</option><option value="active">Active</option><option value="pending">Pending</option><option value="suspended">Suspended</option></select></div>
      <div className="admin-resource-table"><div className="admin-resource-head admin-user-row"><span>User</span><span>Role</span><span>Status</span><span>Summary</span><span>Actions</span></div>{users.map(user => <div className="admin-resource-row admin-user-row" key={user.id}><div><strong>{user.name}</strong><small>{user.identifier}</small></div><select value={user.role} onChange={e => void access(user, { role: e.target.value })}><option value="student">Student</option><option value="lecturer">Lecturer</option><option value="administrator">Administrator</option></select><span className={`resource-status ${user.status}`}>{user.status}</span><small>{user.profile?.course || 'No course'} · {user.verified ? 'verified' : 'unverified'}</small><div><button onClick={() => void inspect(user)}>View</button><button onClick={() => void access(user, { status: user.status === 'suspended' ? 'active' : 'suspended' })}>{user.status === 'suspended' ? 'Reactivate' : 'Suspend'}</button>{user.role === 'lecturer' && !user.verified && <button onClick={() => void resend(user)}>Resend code</button>}</div></div>)}</div>
    </section>
    {selected && <section className="admin-activity-grid"><article><p>USER SUMMARY</p><strong>{selected.name}</strong><small>{selected.role} · {selected.status}</small></article><article><p>USER AUDIT HISTORY</p>{audit.length ? audit.map(item => <div key={`${item.action}${item.createdAt}`}><strong>{item.action.replaceAll('_', ' ')}</strong><small>{new Date(item.createdAt).toLocaleString()}</small></div>) : <small>No audit events.</small>}</article></section>}
  </PageIntro>
}
