import { useEffect, useMemo, useState } from 'react'
import { Icon, PageIntro } from '../components/ui'
import type { IconName } from '../types'

type Status = 'draft' | 'published' | 'archived'
type AdminResource = { id: string; title: string; author: string; description: string | null; resourceType: string; category: string | null; subject: string | null; course: string | null; tags: string[] | string | null; publicationYear: number | null; filePath: string | null; pageCount: number | null; status: Status; createdAt: string; updatedAt: string }
type Dashboard = { metrics: { totalUsers: number; activeUsers: number; published: number; drafts: number; archived: number; aiRequests: number; activeReaders: number; averageProgress: number }; registrations: { name: string; role: string; createdAt: string }[]; uploads: { title: string; status: string; createdAt: string }[]; failedProcessing: { title: string; status: string; updatedAt: string }[] }
type Form = { title: string; author: string; description: string; category: string; subject: string; course: string; tags: string; resourceType: string; publicationYear: string; pageCount: string; status: Status }
const blank: Form = { title: '', author: '', description: '', category: '', subject: '', course: '', tags: '', resourceType: 'pdf', publicationYear: '', pageCount: '', status: 'draft' }

const toBase64 = async (file: File) => {
  const bytes = new Uint8Array(await file.arrayBuffer()); let binary = ''
  for (let i = 0; i < bytes.length; i += 0x8000) binary += String.fromCharCode(...bytes.subarray(i, i + 0x8000))
  return btoa(binary)
}

export function AdminResourcesPage({ token, setToast }: { token: string | null; setToast: (message: string) => void }) {
  const [dashboard, setDashboard] = useState<Dashboard | null>(null)
  const [items, setItems] = useState<AdminResource[]>([])
  const [query, setQuery] = useState(''); const [status, setStatus] = useState<'all' | Status>('all'); const [category, setCategory] = useState('')
  const [rangeDays, setRangeDays] = useState(30); const [dateFrom, setDateFrom] = useState(''); const [dateTo, setDateTo] = useState('')
  const [selected, setSelected] = useState<string[]>([]); const [editing, setEditing] = useState<AdminResource | null>(null); const [creating, setCreating] = useState(false)
  const [form, setForm] = useState<Form>(blank); const [file, setFile] = useState<File | null>(null); const [busy, setBusy] = useState(false); const [progress, setProgress] = useState<number | null>(null); const [audit, setAudit] = useState<{ action: string; createdAt: string }[]>([])
  const headers: Record<string, string> = token ? { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' } : {}
  const request = async <T,>(url: string, init?: RequestInit) => { const response = await fetch(url, { ...init, headers: { ...headers, ...(init?.headers ?? {}) } }); const body = await response.json().catch(() => ({})); if (!response.ok || !body.ok) throw new Error(body.error ?? 'Request failed.'); return body as T }
  const load = async () => {
    if (!token) return
    try { const params = new URLSearchParams(); if (query) params.set('q', query); if (status !== 'all') params.set('status', status); if (category) params.set('category', category); if (dateFrom) params.set('from', dateFrom); if (dateTo) params.set('to', dateTo); const [metrics, catalog] = await Promise.all([request<Dashboard>(`/api/admin/dashboard?days=${rangeDays}`), request<{ resources: AdminResource[] }>(`/api/admin/resources?${params}`)]); setDashboard(metrics); setItems(catalog.resources) } catch (error) { setToast(error instanceof Error ? error.message : 'Could not load administration data.') }
  }
  useEffect(() => { void load() }, [token, query, status, category, rangeDays, dateFrom, dateTo])
  const categories = useMemo(() => [...new Set(items.flatMap(item => [item.category, item.subject, item.course]).filter(Boolean) as string[])], [items])
  const closeEditor = () => { setCreating(false); setEditing(null); setFile(null); setForm(blank); setAudit([]) }
  const openEditor = (item?: AdminResource) => {
    setCreating(!item); setEditing(item ?? null); setFile(null); setAudit([])
    setForm(item ? { title: item.title, author: item.author, description: item.description ?? '', category: item.category ?? '', subject: item.subject ?? '', course: item.course ?? '', tags: Array.isArray(item.tags) ? item.tags.join(', ') : item.tags ?? '', resourceType: item.resourceType, publicationYear: String(item.publicationYear ?? ''), pageCount: String(item.pageCount ?? ''), status: item.status } : blank)
    if (item) void request<{ history: { action: string; createdAt: string }[] }>(`/api/admin/resources/${item.id}/audit`).then(result => setAudit(result.history)).catch(() => setAudit([]))
  }
  const upload = (url: string, method: 'POST' | 'PATCH', payload: Record<string, unknown>) => new Promise<void>((resolve, reject) => { const xhr = new XMLHttpRequest(); xhr.open(method, url); if (token) xhr.setRequestHeader('Authorization', `Bearer ${token}`); xhr.setRequestHeader('Content-Type', 'application/json'); xhr.upload.onprogress = event => { if (event.lengthComputable) setProgress(Math.round(event.loaded / event.total * 100)) }; xhr.onerror = () => reject(new Error('The file upload could not reach the server.')); xhr.onload = () => { const result = JSON.parse(xhr.responseText || '{}'); xhr.status >= 200 && xhr.status < 300 && result.ok ? resolve() : reject(new Error(result.error ?? 'The file upload failed.')) }; xhr.send(JSON.stringify(payload)) })
  const submit = async (event: React.FormEvent) => {
    event.preventDefault(); if (!token) return
    if (file && (file.type !== 'application/pdf' || file.size > 50 * 1024 * 1024)) return setToast('Choose a PDF no larger than 50 MB.')
    setBusy(true); setProgress(file ? 0 : null)
    try { const payload: Record<string, unknown> = { ...form, tags: form.tags.split(',').map(tag => tag.trim()).filter(Boolean) }; const url = editing ? `/api/admin/resources/${editing.id}` : '/api/admin/resources'; const method = editing ? 'PATCH' : 'POST'; if (file) { payload.fileData = await toBase64(file); payload.fileName = file.name; payload.fileType = file.type; payload.fileSizeBytes = file.size; await upload(url, method, payload) } else await request(url, { method, body: JSON.stringify(payload) }); setToast(editing ? 'Resource updated.' : 'Resource created.'); closeEditor(); await load() } catch (error) { setToast(error instanceof Error ? error.message : 'Could not save the resource.') } finally { setBusy(false); setProgress(null) }
  }
  const changeStatus = async (ids: string[], next: Status) => { if (!ids.length) return; setBusy(true); try { await Promise.all(ids.map(id => request(`/api/admin/resources/${id}`, { method: 'PATCH', body: JSON.stringify({ status: next }) }))); setSelected([]); setToast(`${ids.length} resource${ids.length === 1 ? '' : 's'} updated.`); await load() } catch (error) { setToast(error instanceof Error ? error.message : 'Status update failed.') } finally { setBusy(false) } }
  const remove = async (item: AdminResource) => { if (!window.confirm(`Delete “${item.title}” and its uploaded file? This cannot be undone.`)) return; try { await request(`/api/admin/resources/${item.id}`, { method: 'DELETE' }); setToast('Resource deleted.'); await load() } catch (error) { setToast(error instanceof Error ? error.message : 'Could not delete the resource.') } }
  const metrics: [IconName, string | number, string, string][] = [['users', dashboard?.metrics.totalUsers ?? '–', 'Total users', `${dashboard?.metrics.activeUsers ?? 0} active`], ['book', dashboard?.metrics.published ?? '–', 'Published', `${dashboard?.metrics.drafts ?? 0} drafts`], ['file', dashboard?.metrics.archived ?? '–', 'Archived', 'Not discoverable'], ['sparkle', dashboard?.metrics.aiRequests ?? '–', 'AI requests', 'Usage metadata'], ['trend', dashboard?.metrics.activeReaders ?? '–', 'Active readers', `${dashboard?.metrics.averageProgress ?? 0}% average progress`]]
  return <PageIntro eyebrow="LIBRARY ADMINISTRATION" title="Resources & insights" copy="Publish, maintain, and audit the learning catalogue." action="Add resource" onAction={() => openEditor()}>
    <section className="lecturer-metrics">{metrics.map(([icon, value, label, note]) => <article className="lecturer-metric" key={label}><span><Icon name={icon} /></span><strong>{value}</strong><p>{label}</p><small>{note}</small></article>)}</section>
    <section className="admin-resource-card"><div className="lecturer-section-head"><div><p>CATALOGUE CONTROL</p><h3>Resource administration</h3></div><button onClick={() => void load()}><Icon name="trend" size={15} />Refresh</button></div>
      <div className="admin-filters"><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search title, author, subject, course" /><select value={status} onChange={event => setStatus(event.target.value as 'all' | Status)}><option value="all">All statuses</option><option value="published">Published</option><option value="draft">Drafts</option><option value="archived">Archived</option></select><select value={category} onChange={event => setCategory(event.target.value)}><option value="">All categories</option>{categories.map(value => <option key={value}>{value}</option>)}</select><input type="date" value={dateFrom} onChange={event => setDateFrom(event.target.value)} aria-label="Created after" /><input type="date" value={dateTo} onChange={event => setDateTo(event.target.value)} aria-label="Created before" /><select value={rangeDays} onChange={event => setRangeDays(Number(event.target.value))}><option value={7}>Last 7 days</option><option value={30}>Last 30 days</option><option value={90}>Last 90 days</option><option value={365}>Last year</option></select></div>
      {selected.length > 0 && <div className="bulk-actions"><span>{selected.length} selected</span><button onClick={() => void changeStatus(selected, 'published')}>Publish</button><button onClick={() => void changeStatus(selected, 'draft')}>Unpublish</button><button onClick={() => void changeStatus(selected, 'archived')}>Archive</button></div>}
      <div className="admin-resource-table"><div className="admin-resource-head"><span /><span>Resource</span><span>Status</span><span>File / updated</span><span>Actions</span></div>{items.map(item => <div className="admin-resource-row" key={item.id}><input type="checkbox" checked={selected.includes(item.id)} onChange={() => setSelected(current => current.includes(item.id) ? current.filter(id => id !== item.id) : [...current, item.id])} /><div><strong>{item.title}</strong><small>{item.author} · {item.course || item.subject || item.category || 'Uncategorised'}</small></div><span className={`resource-status ${item.status}`}>{item.status}</span><small>{item.filePath ? 'PDF attached' : 'No file'} · {new Date(item.updatedAt).toLocaleDateString()}</small><div><button onClick={() => openEditor(item)}>Edit</button><button onClick={() => void changeStatus([item.id], item.status === 'published' ? 'draft' : 'published')}>{item.status === 'published' ? 'Unpublish' : 'Publish'}</button><button className="delete-student" onClick={() => void remove(item)}>Delete</button></div></div>)}{!items.length && <p className="admin-empty">No resources match these filters.</p>}</div>
    </section>
    <section className="admin-activity-grid"><article><p>RECENT UPLOADS</p>{dashboard?.uploads.length ? dashboard.uploads.map(item => <div key={`${item.title}${item.createdAt}`}><strong>{item.title}</strong><small>{item.status} · {new Date(item.createdAt).toLocaleDateString()}</small></div>) : <small>No upload activity yet.</small>}</article><article><p>RECENT REGISTRATIONS</p>{dashboard?.registrations.length ? dashboard.registrations.map(item => <div key={`${item.name}${item.createdAt}`}><strong>{item.name}</strong><small>{item.role} · {new Date(item.createdAt).toLocaleDateString()}</small></div>) : <small>No registration activity yet.</small>}</article><article><p>FILE / PROCESSING FLAGS</p>{dashboard?.failedProcessing.length ? dashboard.failedProcessing.map(item => <div key={`${item.title}${item.updatedAt}`}><strong>{item.title}</strong><small>{item.status} · file needs attention</small></div>) : <small>No failed uploads or missing files.</small>}</article></section>
    {(creating || editing) && <div className="admin-modal" role="dialog" aria-modal="true" aria-label="Resource editor"><form onSubmit={submit}><div className="lecturer-section-head"><div><p>{editing ? 'EDIT RESOURCE' : 'NEW RESOURCE'}</p><h3>{editing?.title ?? 'Add a resource'}</h3></div><button type="button" onClick={closeEditor}>Close</button></div><label>Title<input required value={form.title} onChange={event => setForm({ ...form, title: event.target.value })} /></label><label>Author<input required value={form.author} onChange={event => setForm({ ...form, author: event.target.value })} /></label><label>Description<textarea value={form.description} onChange={event => setForm({ ...form, description: event.target.value })} /></label><div className="admin-form-grid"><label>Category<input value={form.category} onChange={event => setForm({ ...form, category: event.target.value })} /></label><label>Subject<input value={form.subject} onChange={event => setForm({ ...form, subject: event.target.value })} /></label><label>Course<input value={form.course} onChange={event => setForm({ ...form, course: event.target.value })} /></label><label>Tags (comma-separated)<input value={form.tags} onChange={event => setForm({ ...form, tags: event.target.value })} /></label><label>Type<select value={form.resourceType} onChange={event => setForm({ ...form, resourceType: event.target.value })}><option value="pdf">PDF book</option><option value="book">Book</option><option value="journal">Journal</option><option value="article">Article</option><option value="other">Other</option></select></label><label>Year<input type="number" value={form.publicationYear} onChange={event => setForm({ ...form, publicationYear: event.target.value })} /></label><label>Page count<input type="number" value={form.pageCount} onChange={event => setForm({ ...form, pageCount: event.target.value })} /></label><label>Status<select value={form.status} onChange={event => setForm({ ...form, status: event.target.value as Status })}><option value="draft">Draft</option><option value="published">Published</option><option value="archived">Archived</option></select></label></div><label>PDF file {editing && '(leave empty to keep current file)'}<input type="file" accept="application/pdf,.pdf" onChange={event => setFile(event.target.files?.[0] ?? null)} />{file && <small>{file.name} · {(file.size / 1024 / 1024).toFixed(1)} MB</small>}</label>{progress !== null && <p className="upload-progress">Uploading PDF: {progress}%</p>}{editing && <div className="admin-audit"><p>RESOURCE AUDIT HISTORY</p>{audit.length ? audit.map(event => <small key={`${event.action}${event.createdAt}`}>{event.action.replaceAll('_', ' ')} · {new Date(event.createdAt).toLocaleString()}</small>) : <small>No audit events yet.</small>}</div>}<button className="primary-button" disabled={busy}>{busy ? 'Saving…' : editing ? 'Save changes' : 'Create resource'}</button></form></div>}
  </PageIntro>
}
