import { useMemo, useState } from 'react'
import type { Resource } from '../types'
import { Empty, Icon, PageIntro, ResourceCard } from '../components/ui'

type Sort = 'relevance' | 'title' | 'author' | 'date' | 'popular'
const pageSize = 6

export function DiscoverPage({ resources, query, setQuery, showResource, saved, toggleSaved }: { resources: Resource[]; query: string; setQuery: (query: string) => void; showResource: (resource: Resource) => void; saved: number[]; toggleSaved: (resource: Resource) => void }) {
  const [subject, setSubject] = useState('All subjects'); const [course, setCourse] = useState('All courses'); const [type, setType] = useState('All resource types'); const [language, setLanguage] = useState('All languages'); const [availability, setAvailability] = useState('All availability'); const [sort, setSort] = useState<Sort>('relevance'); const [page, setPage] = useState(1)
  const [recent, setRecent] = useState<string[]>(() => JSON.parse(localStorage.getItem('cresa-recent-searches') ?? '[]'))
  const subjects = [...new Set(resources.map(item => item.kind))]; const courses = [...new Set(resources.map(item => item.courseCode))]
  const filtered = useMemo(() => resources.filter(item => { const needle = query.trim().toLowerCase(); const text = [item.title, item.author, item.kind, item.courseCode, item.identifier, ...item.keywords].join(' ').toLowerCase(); return (!needle || text.includes(needle)) && (subject === 'All subjects' || item.kind === subject) && (course === 'All courses' || item.courseCode === course) && (type === 'All resource types' || item.format === type) && (language === 'All languages' || item.language === language) && (availability === 'All availability' || item.availability === availability) }).sort((a, b) => sort === 'title' ? a.title.localeCompare(b.title) : sort === 'author' ? a.author.localeCompare(b.author) : sort === 'date' ? b.addedAt.localeCompare(a.addedAt) : sort === 'popular' ? b.progress - a.progress : 0), [resources, query, subject, course, type, language, availability, sort])
  const shown = filtered.slice(0, page * pageSize)
  const clear = () => { setQuery(''); setSubject('All subjects'); setCourse('All courses'); setType('All resource types'); setLanguage('All languages'); setAvailability('All availability'); setSort('relevance'); setPage(1) }
  const remember = () => { const value = query.trim(); if (!value) return; const next = [value, ...recent.filter(item => item.toLowerCase() !== value.toLowerCase())].slice(0, 5); setRecent(next); localStorage.setItem('cresa-recent-searches', JSON.stringify(next)) }
  const select = (label: string, value: string, options: string[], setter: (next: string) => void) => <label>{label}<select value={value} onChange={event => { setter(event.target.value); setPage(1) }}><option>{`All ${label.toLowerCase()}s`}</option>{options.map(item => <option key={item}>{item}</option>)}</select></label>
  return <PageIntro eyebrow="CRESA LEARNING LIBRARY" title="Explore the catalogue" copy="Search, filter, and save the course materials you need."><section className="catalog-hero"><div className="discover-search"><Icon name="search" /><input value={query} onBlur={remember} onChange={event => { setQuery(event.target.value); setPage(1) }} onKeyDown={event => event.key === 'Enter' && remember()} placeholder="Search title, author, keyword, course, or identifier" /><button type="button" onClick={clear}>Clear</button></div>{recent.length > 0 && !query && <div className="recent-searches"><span>Recent searches</span>{recent.map(item => <button key={item} onClick={() => setQuery(item)}>{item}</button>)}<button onClick={() => { setRecent([]); localStorage.removeItem('cresa-recent-searches') }}>Clear history</button></div>}<div className="catalog-feature-row"><span><Icon name="sparkle" />Featured resources</span><span><Icon name="clock" />Recently added</span><span><Icon name="trend" />Popular this week</span><span><Icon name="bookmark" />Recommended</span></div></section><div className="catalog-layout"><aside className="catalog-aside filter-panel"><div><p>FILTER RESULTS</p><button className="filter-clear" onClick={clear}>Clear all</button></div>{select('Subject', subject, subjects, setSubject)}{select('Course', course, courses, setCourse)}{select('Resource type', type, [...new Set(resources.map(item => item.format))], setType)}{select('Language', language, ['English'], setLanguage)}{select('Availability', availability, ['Available'], setAvailability)}</aside><section className="catalog-results"><div className="catalog-result-head"><p><b>{filtered.length}</b> resources found</p><label>Sort by<select value={sort} onChange={event => { setSort(event.target.value as Sort); setPage(1) }}><option value="relevance">Relevance</option><option value="title">Title</option><option value="author">Author</option><option value="date">Date added</option><option value="popular">Popularity</option></select></label></div>{shown.length ? <><div className="book-grid catalog-grid">{shown.map(resource => <ResourceCard key={resource.id} resource={resource} onClick={() => showResource(resource)} saved={saved.includes(resource.id)} onSave={() => toggleSaved(resource)} />)}</div>{shown.length < filtered.length && <button className="load-more" onClick={() => setPage(current => current + 1)}>Load more books <Icon name="arrow" size={15} /></button>}</> : <Empty icon="search" title="No resources match those filters" copy="Try a title, course code, author, or use Clear all to see the full library." />}</section></div></PageIntro>
}
