import 'dart:async';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'models.dart';
import 'services.dart';
import 'theme.dart';
import 'screens.dart';
import 'bot.dart';

class CresaApp extends StatefulWidget { const CresaApp({super.key}); @override State<CresaApp> createState() => _CresaAppState(); }
class _CresaAppState extends State<CresaApp> {
  final api = CresaApi(httpClient());
  final session = SessionStore();
  String? token; AuthUser? user; bool ready = false;
  @override void initState() { super.initState(); session.read().then((saved) { if (!mounted) return; setState(() { token = saved.$1; user = saved.$2; ready = true; }); }); }
  @override Widget build(BuildContext context) => MaterialApp(debugShowCheckedModeBanner: false, title: 'Cresa E-library', theme: CresaTheme.light(), home: !ready ? const Scaffold(body: Center(child: CircularProgressIndicator())) : token == null || user == null ? LoginPage(api: api, session: session, onLogin: (value) => setState(() { token = value.$1; user = value.$2; })) : HomeShell(api: api, session: session, token: token!, user: user!, onLogout: () => setState(() { token = null; user = null; }));
}

http.Client httpClient() => http.Client();

class LoginPage extends StatefulWidget { const LoginPage({super.key, required this.api, required this.session, required this.onLogin}); final CresaApi api; final SessionStore session; final void Function((String, AuthUser)) onLogin; @override State<LoginPage> createState() => _LoginPageState(); }
class _LoginPageState extends State<LoginPage> {
  final identifier = TextEditingController(); final password = TextEditingController(); final name = TextEditingController(); final email = TextEditingController(); bool register = false; bool lecturer = false; bool busy = false; String? error;
  @override void dispose() { identifier.dispose(); password.dispose(); name.dispose(); email.dispose(); super.dispose(); }
  Future<void> submit() async { setState(() { busy = true; error = null; }); final result = register ? await widget.api.register({'name': name.text.trim(), 'identifier': identifier.text.trim(), 'password': password.text, 'role': lecturer ? 'lecturer' : 'student', if (lecturer) 'lecturerEmail': email.text.trim()}) : await widget.api.login(identifier.text.trim(), password.text); if (!mounted) return; if (!result.ok) { setState(() { error = result.error; busy = false; }); return; } if (register) { setState(() { register = false; busy = false; error = 'Account created. Sign in to continue.'; }); return; } final account = AuthUser.fromJson(Map<String, dynamic>.from(result.data!['user'] as Map)); final sessionToken = '${result.data!['sessionToken']}'; await widget.session.save(sessionToken, account); widget.onLogin((sessionToken, account)); }
  @override Widget build(BuildContext context) => Scaffold(body: SafeArea(child: ListView(padding: const EdgeInsets.fromLTRB(24, 38, 24, 24), children: [const CresaLogo(size: 72), const SizedBox(height: 20), Text('Cresa E-library', style: Theme.of(context).textTheme.headlineSmall?.copyWith(fontWeight: FontWeight.w800, color: CresaTheme.ink)), const SizedBox(height: 6), Text(register ? 'Create your learning space.' : 'Welcome back to your reading space.', style: const TextStyle(color: CresaTheme.muted)), const SizedBox(height: 28), if (error != null) Container(padding: const EdgeInsets.all(12), margin: const EdgeInsets.only(bottom: 14), decoration: BoxDecoration(color: error!.startsWith('Account') ? const Color(0xffe9f8f1) : const Color(0xffffeef2), borderRadius: BorderRadius.circular(12)), child: Text(error!, style: TextStyle(color: error!.startsWith('Account') ? Colors.green.shade700 : Colors.red.shade700))), if (register) TextField(controller: name, decoration: const InputDecoration(labelText: 'Full name')), if (register) const SizedBox(height: 12), if (register) SegmentedButton<bool>(segments: const [ButtonSegment(value: false, label: Text('Student')), ButtonSegment(value: true, label: Text('Lecturer'))], selected: {lecturer}, onSelectionChanged: (value) => setState(() => lecturer = value.first)), if (register) const SizedBox(height: 12), if (register && lecturer) TextField(controller: email, keyboardType: TextInputType.emailAddress, decoration: const InputDecoration(labelText: 'Lecturer email')), if (register && lecturer) const SizedBox(height: 12), TextField(controller: identifier, decoration: InputDecoration(labelText: register ? (lecturer ? 'Lecturer ID' : 'Registration number') : 'Registration number or Lecturer ID')), const SizedBox(height: 12), TextField(controller: password, obscureText: true, decoration: const InputDecoration(labelText: 'Password')), const SizedBox(height: 20), FilledButton(onPressed: busy ? null : submit, child: Text(busy ? 'Please wait...' : register ? 'Create account' : 'Sign in')), const SizedBox(height: 12), TextButton(onPressed: () => setState(() { register = !register; error = null; }), child: Text(register ? 'Already have an account? Sign in' : 'New to Cresa? Create account'))])));
}

class HomeShell extends StatefulWidget { const HomeShell({super.key, required this.api, required this.session, required this.token, required this.user, required this.onLogout}); final CresaApi api; final SessionStore session; final String token; final AuthUser user; final VoidCallback onLogout; @override State<HomeShell> createState() => _HomeShellState(); }
class _HomeShellState extends State<HomeShell> {
  int index = 0; int unread = 0; Timer? timer;
  final titles = const ['Overview', 'My Library', 'Discover', 'Community', 'Settings'];
  @override void initState() { super.initState(); refreshNotifications(); timer = Timer.periodic(const Duration(seconds: 15), (_) => refreshNotifications()); }
  @override void dispose() { timer?.cancel(); super.dispose(); }
  Future<void> refreshNotifications() async { final result = await widget.api.notifications(widget.token); if (mounted && result.ok) setState(() => unread = result.data!.where((item) => item.readAt == null).length); }
  void openPage(int value) { setState(() => index = value); if (value == 3) { widget.api.readNotifications(widget.token); setState(() => unread = 0); } }
  @override Widget build(BuildContext context) { final pages = [OverviewPage(user: widget.user, onOpen: openPage), LibraryPage(api: widget.api, token: widget.token), const DiscoverPage(), CommunityPage(api: widget.api, token: widget.token, user: widget.user), SettingsPage(api: widget.api, token: widget.token, user: widget.user, onLogout: widget.onLogout)]; return Scaffold(appBar: AppBar(title: Row(children: [const CresaLogo(size: 30), const SizedBox(width: 9), Text(titles[index], style: const TextStyle(fontWeight: FontWeight.w800))]), actions: [IconButton(onPressed: () => showNotifications(context), icon: Badge(isLabelVisible: unread > 0, label: Text('$unread'), child: const Icon(Icons.notifications_none_rounded))), const SizedBox(width: 8)]), body: IndexedStack(index: index, children: pages), floatingActionButton: FloatingActionButton.extended(onPressed: () => showModalBottomSheet(context: context, isScrollControlled: true, showDragHandle: true, builder: (_) => CresaBotSheet(api: widget.api, token: widget.token)), icon: const Icon(Icons.auto_awesome_rounded), label: const Text('CresaBot')), bottomNavigationBar: NavigationBar(selectedIndex: index, onDestinationSelected: openPage, destinations: [const NavigationDestination(icon: Icon(Icons.grid_view_rounded), label: 'Overview'), const NavigationDestination(icon: Icon(Icons.menu_book_rounded), label: 'Library'), const NavigationDestination(icon: Icon(Icons.explore_outlined), label: 'Discover'), NavigationDestination(icon: Badge(isLabelVisible: unread > 0, label: Text('$unread'), child: const Icon(Icons.groups_rounded)), label: 'Community'), const NavigationDestination(icon: Icon(Icons.settings_outlined), label: 'Settings')]) ); }
  Future<void> showNotifications(BuildContext context) async { final result = await widget.api.notifications(widget.token); if (!context.mounted) return; showModalBottomSheet(context: context, showDragHandle: true, builder: (_) => SafeArea(child: result.ok && result.data!.isNotEmpty ? ListView(padding: const EdgeInsets.all(18), children: [Text('Notifications', style: Theme.of(context).textTheme.titleLarge?.copyWith(fontWeight: FontWeight.w800)), const SizedBox(height: 12), ...result.data!.map((item) => ListTile(leading: Icon(item.type == 'reaction' ? Icons.favorite_rounded : item.type == 'comment' ? Icons.chat_bubble_rounded : Icons.alternate_email_rounded, color: CresaTheme.blue), title: Text(item.message), subtitle: Text(item.createdAt.toLocal().toString())))]): const Padding(padding: EdgeInsets.all(30), child: Text('No notifications yet.')))); }
}

class OverviewPage extends StatelessWidget { const OverviewPage({super.key, required this.user, required this.onOpen}); final AuthUser user; final ValueChanged<int> onOpen; @override Widget build(BuildContext context) => ListView(padding: const EdgeInsets.all(18), children: [Container(padding: const EdgeInsets.all(22), decoration: BoxDecoration(gradient: const LinearGradient(colors: [CresaTheme.navy, CresaTheme.blue]), borderRadius: BorderRadius.circular(24)), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text('YOUR LEARNING SPACE', style: TextStyle(color: Colors.blue.shade100, fontSize: 11, fontWeight: FontWeight.w700)), const SizedBox(height: 10), Text('Make room for brilliant ideas.', style: Theme.of(context).textTheme.headlineMedium?.copyWith(color: Colors.white, fontWeight: FontWeight.w800)), const SizedBox(height: 10), const Text('Build a personal library, make time to read, and return to the thoughts that matter.', style: TextStyle(color: Colors.white70)), const SizedBox(height: 18), FilledButton.tonal(onPressed: () => onOpen(2), child: const Text('Explore library'))])), const SizedBox(height: 18), Row(children: [Expanded(child: stat(context, 'Books in progress', '00')), const SizedBox(width: 10), Expanded(child: stat(context, 'Reading time', '0')), const SizedBox(width: 10), Expanded(child: stat(context, 'Completed', '00'))]), const SizedBox(height: 24), Text('Continue reading', style: Theme.of(context).textTheme.titleLarge?.copyWith(fontWeight: FontWeight.w800, color: CresaTheme.ink)), const SizedBox(height: 10), const CresaCard(child: ListTile(leading: Icon(Icons.menu_book_rounded, color: CresaTheme.blue), title: Text('Problem Solving'), subtitle: Text('CRESA Learning Library'), trailing: Icon(Icons.arrow_forward_rounded)))]; }
  Widget stat(BuildContext context, String label, String value) => CresaCard(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(label, style: const TextStyle(color: CresaTheme.muted, fontSize: 11)), const SizedBox(height: 7), Text(value, style: Theme.of(context).textTheme.headlineSmall?.copyWith(fontWeight: FontWeight.w800, color: CresaTheme.ink))]));
}
