import { useState, type FormEvent } from 'react'
import { Icon } from '../components/ui'
import { passwordIssue, resetPassword, type AuthUser, type Role, saveSession, validStudentRegistration } from './store'
import { registerLecturerAccount, sendLecturerVerificationCode, verifyLecturerCode } from './verification'
import { api } from './api'

type Mode = 'login' | 'register' | 'verify' | 'forgot' | 'reset'

export function AuthPage({ onAuthenticated }: { onAuthenticated: (user: AuthUser) => void }) {
  const [mode, setMode] = useState<Mode>('login')
  const [name, setName] = useState('')
  const [identifier, setIdentifier] = useState('')
  const [password, setPassword] = useState('')
  const [showPassword, setShowPassword] = useState(false)
  const [role, setRole] = useState<Exclude<Role, 'administrator'>>('student')
  const [lecturerEmail, setLecturerEmail] = useState('')
  const [verificationCode, setVerificationCode] = useState('')
  const [error, setError] = useState('')
  const [notice, setNotice] = useState('')
  const [busy, setBusy] = useState(false)

  const identifierLabel = role === 'student' ? 'Registration number' : 'Lecturer ID'
  const identifierPlaceholder = role === 'student' ? 'e.g. 21/VL/CR/0012' : 'e.g. LEC/2026/0042'
  const switchMode = (next: Mode) => { setMode(next); setError(''); setNotice(''); setPassword(''); setShowPassword(false) }
  const run = (callback: () => Promise<void> | void) => { setBusy(true); window.setTimeout(async () => { await callback(); setBusy(false) }, 350) }
  const resendLecturerCode = () => run(async () => {
    try {
      const result = await sendLecturerVerificationCode({ lecturerId: identifier, email: lecturerEmail })
      if (result.ok) setNotice('A new six-digit code was generated. Check the local verification server terminal.')
      else setError(result.error ?? 'Could not generate a new verification code.')
    } catch { setError('Verification service is unavailable. Start the local verification server and try again.') }
  })
  const submit = async (event: FormEvent) => {
    event.preventDefault()
    setError('')
    if (mode === 'login') return run(async () => {
      const result = await api.login(identifier, password)
      if (!result.ok) { setError(result.error); return }
      sessionStorage.setItem('cresa_show_welcome', 'true')
      saveSession(result.data.user, result.data.sessionToken)
      onAuthenticated(result.data.user)
    })
    if (mode === 'register') return run(async () => {
      if (role === 'student' && !validStudentRegistration(identifier)) { setError('Student registration numbers must follow 00/VL/CR/000 or 00/VL/CR/0000.'); return }
      const result = role === 'lecturer'
        ? await registerLecturerAccount({ name, lecturerId: identifier, email: lecturerEmail, password })
        : await api.register({ name, identifier, password, role })
      if (!result.ok) { setError(result.error ?? 'Could not create the account.'); return }
      if (role === 'lecturer') {
        setNotice('Account created. Your verification code is available in the local Node.js backend terminal.')
        setMode('verify')
      } else { setNotice('Account created. Sign in to continue.'); setMode('login') }
    })
    if (mode === 'verify') return run(async () => {
      if (role === 'lecturer') {
        if (!/^\d{6}$/.test(verificationCode)) { setError('Enter the 6-digit verification code.'); return }
        try {
          const codeResult = await verifyLecturerCode({ lecturerId: identifier, code: verificationCode })
          if (!codeResult.ok) { setError(codeResult.error ?? 'That verification code is invalid.'); return }
        } catch { setError('Verification service is unavailable. Start the local verification server and try again.'); return }
      }
      const loginResult = await api.login(identifier, password)
      if (!loginResult.ok) { setError(loginResult.error); return }
      saveSession(loginResult.data.user, loginResult.data.sessionToken)
      onAuthenticated(loginResult.data.user)
    })
    if (mode === 'forgot') return run(() => { if (!identifier.trim()) { setError('Enter your registration number or Lecturer ID.'); return }; setNotice('Reset link prepared for this local preview. Choose a new password below.'); setMode('reset') })
    return run(() => { const result = resetPassword(identifier, password); if (result.ok) { setNotice('Password updated. You can now sign in.'); setMode('login') } else setError(result.error) })
  }

  const title = { login: 'Welcome back', register: 'Create your space', verify: 'Verify your account', forgot: 'Reset your password', reset: 'Choose a new password' }[mode]
  const subtitle = { login: 'Sign in to continue your reading journey.', register: 'Start with an account built around your curiosity.', verify: role === 'lecturer' ? 'Enter the six-digit code generated by the local verification server.' : 'In this local preview, confirm your account to activate it.', forgot: 'Enter the identifier registered to your account.', reset: 'Use a strong password you have not used elsewhere.' }[mode]
  const submitText = { login: 'Sign in', register: 'Create account', verify: 'Verify account and continue', forgot: 'Continue', reset: 'Reset password' }[mode]
  const passwordHelp = password ? passwordIssue(password) : ''

  return (
    <main className="auth-page">
      <section className="auth-panel">
        <div className="auth-brand">
          <img src="/assets/cresa-e-library-logo-circle.png" alt="Cresa E-library logo" style={{ width: 40, height: 40, objectFit: 'cover', borderRadius: '50%' }} />
          <strong>Cresa <span>E-library</span></strong>
        </div>

        <div className="auth-copy">
          <p><Icon name="sparkle" size={15} /> A considered place for learning</p>
          <h1>Find room for<br /><em>better ideas.</em></h1>
          <span>Build a personal library, make time to read, and return to the thoughts that matter.</span>
          <div className="auth-orb auth-orb-one" />
          <div className="auth-orb auth-orb-two" />
        </div>

        <div className="auth-float auth-float-book">THE<br />NEXT<br /><b>IDEA</b><small>YOUR LIBRARY</small></div>
        <div className="auth-float auth-float-card"><Icon name="sparkle" size={16} /><strong>12 ideas saved</strong><span>for later</span></div>
        <div className="auth-float auth-float-note"><Icon name="bookmark" size={15} /> Read slowly</div>
        <div className="auth-float auth-float-dot" />
        <div className="auth-float auth-float-ring" />

        <div className="auth-stats">
          <div><strong>6,000+</strong><span>resources to explore</span></div>
          <div><strong>12k</strong><span>readers learning</span></div>
        </div>
      </section>

      <section className="auth-form-side">
        <div className="auth-form-wrap">
          <div className="auth-topline">
            <span>{mode === 'login' ? 'New to Cresa?' : 'Already have an account?'}</span>
            <button onClick={() => switchMode(mode === 'login' ? 'register' : 'login')}>{mode === 'login' ? 'Create account' : 'Sign in'}</button>
          </div>

          <form className="auth-form" onSubmit={submit}>
            <div>
              <img src="/assets/cresa-e-library-logo-circle.png" alt="Cresa E-library crest" style={{ display: 'block', width: 86, height: 86, marginBottom: 18, objectFit: 'cover', borderRadius: '50%' }} />
              <p className="auth-eyebrow">CRESA E-LIBRARY</p>
              <h2>{title}</h2>
              <p className="auth-subtitle">{subtitle}</p>
            </div>

            {notice && <div className="auth-notice"><Icon name="check" size={16} />{notice}</div>}
            {error && <div className="auth-error">{error}</div>}

            {mode === 'register' && (
              <label>Full name
                <input value={name} onChange={event => setName(event.target.value)} placeholder="Your full name" autoComplete="name" />
              </label>
            )}

            {mode === 'register' && (
              <fieldset>
                <legend>I am joining as</legend>
                <div className="role-options">
                  <button type="button" className={role === 'student' ? 'selected' : ''} onClick={() => setRole('student')}><Icon name="book" size={17} />Student</button>
                  <button type="button" className={role === 'lecturer' ? 'selected' : ''} onClick={() => setRole('lecturer')}><Icon name="users" size={17} />Lecturer</button>
                </div>
              </fieldset>
            )}

            {mode === 'register' && role === 'lecturer' && (
              <label>Lecturer email address
                <input type="email" value={lecturerEmail} onChange={event => setLecturerEmail(event.target.value)} placeholder="lecturer@university.edu" autoComplete="email" />
                <small className="password-help">Used only to deliver and verify your lecturer account.</small>
              </label>
            )}

            <label>{mode === 'register' ? identifierLabel : 'Registration number or Lecturer ID'}
              <input value={identifier} onChange={event => setIdentifier(event.target.value)} placeholder={mode === 'register' ? identifierPlaceholder : 'Enter your account identifier'} autoComplete="username" />
            </label>

            {mode === 'verify' && role === 'lecturer' && (
              <>
                <label>Verification code
                  <input className="verification-code-input" value={verificationCode} onChange={event => setVerificationCode(event.target.value.replace(/\D/g, '').slice(0, 6))} inputMode="numeric" placeholder="Enter 6-digit code" autoComplete="one-time-code" />
                </label>
                <button type="button" className="auth-link resend-code" onClick={resendLecturerCode}>Generate a new code</button>
              </>
            )}

            {mode !== 'forgot' && mode !== 'verify' && (
              <label>Password
                <span className="password-field"><input type={showPassword ? 'text' : 'password'} value={password} onChange={event => setPassword(event.target.value)} placeholder="Enter your password" autoComplete={mode === 'login' ? 'current-password' : 'new-password'} /><button type="button" aria-label={showPassword ? 'Hide password' : 'Show password'} title={showPassword ? 'Hide password' : 'Show password'} onClick={() => setShowPassword(current => !current)}><Icon name={showPassword ? 'eyeOff' : 'eye'} size={18} /></button></span>
                {(mode === 'register' || mode === 'reset') && <small className={passwordHelp ? 'password-warning' : 'password-help'}>{passwordHelp || '8+ characters, upper & lowercase letters, and a number.'}</small>}
              </label>
            )}

            {mode === 'login' && <button type="button" className="auth-link forgot-link" onClick={() => switchMode('forgot')}>Forgot password?</button>}
            <button className="auth-submit" disabled={busy}>{busy ? 'Please wait...' : submitText} <Icon name="arrow" size={17} /></button>
            {mode === 'register' && <p className="auth-terms">By creating an account, you agree to the library terms and acceptable-use policy.</p>}
          </form>
        </div>
      </section>
    </main>
  )
}
